<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        Product::truncate(); // очищаем таблицу

        Product::insert([
            [
                'name' => 'Lume Arcus Pendant',
                'price' => 420,
                'category_id' => 1,
                'collection_id' => 3,
                'description' => 'Создаёт атмосферу спокойной роскоши.',
                'stock_quantity' => 10,
                'material' => 'Металл',
                'color' => 'Черный',
                'style' => 'Современный',
                'size' => 'M',
                'power' => '10W',
            ],
            [
                'name' => 'NordLight Sphere Halo',
                'price' => 560,
                'category_id' => 1,
                'collection_id' => 3,
                'description' => 'Чистая геометрия и скандинавская простота.',
                'stock_quantity' => 10,
                'material' => 'Стекло',
                'color' => 'Белый',
                'style' => 'Минимализм',
                'size' => 'L',
                'power' => '8W',
            ],
            [
                'name' => 'LoftPro Iron Beam',
                'price' => 310,
                'category_id' => 1,
                'collection_id' => 1,
                'description' => 'Создаёт акцентный свет.',
                'stock_quantity' => 10,
                'material' => 'Металл',
                'color' => 'Черный',
                'style' => 'Лофт',
                'size' => 'XL',
                'power' => '12W',
            ],
            [
                'name' => 'Lume Atelier Desk One',
                'price' => 260,
                'category_id' => 3,
                'collection_id' => 3,
                'description' => 'Идеальна для рабочего пространства.',
                'stock_quantity' => 10,
                'material' => 'Металл',
                'color' => 'Белый',
                'style' => 'Современный',
                'size' => 'S',
                'power' => '6W',
            ],
            [
                'name' => 'SoftGlow Essence Lamp',
                'price' => 180,
                'category_id' => 3,
                'collection_id' => 2,
                'description' => 'Создаёт уютную атмосферу.',
                'stock_quantity' => 10,
                'material' => 'Стекло',
                'color' => 'Золотой',
                'style' => 'Минимализм',
                'size' => 'M',
                'power' => '8W',
            ],
            [
                'name' => 'LoftPro Copper Edge',
                'price' => 320,
                'category_id' => 3,
                'collection_id' => 1,
                'description' => 'Добавляет интерьеру характер.',
                'stock_quantity' => 10,
                'material' => 'Металл',
                'color' => 'Черный',
                'style' => 'Лофт',
                'size' => 'L',
                'power' => '10W',
            ],
            [
                'name' => 'Lume Wall Arc',
                'price' => 240,
                'category_id' => 2,
                'collection_id' => 3,
                'description' => 'Идеально для коридоров.',
                'stock_quantity' => 10,
                'material' => 'Металл',
                'color' => 'Белый',
                'style' => 'Современный',
                'size' => 'S',
                'power' => '6W',
            ],
            [
                'name' => 'SoftGlow Wall Pure',
                'price' => 190,
                'category_id' => 2,
                'collection_id' => 2,
                'description' => 'Добавляет лёгкость.',
                'stock_quantity' => 10,
                'material' => 'Стекло',
                'color' => 'Белый',
                'style' => 'Минимализм',
                'size' => 'M',
                'power' => '8W',
            ],
            [
                'name' => 'LoftPro Wall Forge',
                'price' => 280,
                'category_id' => 2,
                'collection_id' => 1,
                'description' => 'Выразительный световой акцент.',
                'stock_quantity' => 10,
                'material' => 'Металл',
                'color' => 'Черный',
                'style' => 'Лофт',
                'size' => 'L',
                'power' => '12W',
            ],
            [
                'name' => 'Lume Aurelia Pendant',
                'price' => 620,
                'category_id' => 1,
                'collection_id' => 3,
                'description' => 'Роскошь и мягкое освещение.',
                'stock_quantity' => 10,
                'material' => 'Металл',
                'color' => 'Золотой',
                'style' => 'Современный',
                'size' => 'XL',
                'power' => '12W',
            ],
        ]);
    }
}
